# Generated by Django 2.0.9 on 2019-02-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfoTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=100, verbose_name='用户ID')),
                ('status', models.IntegerField(choices=[(0, '未答题'), (1, '已答题')], default=0, verbose_name='答题状态')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户答题状态',
                'verbose_name_plural': '用户答题状态',
            },
        ),
    ]
