# Generated by Django 2.0.9 on 2019-02-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0002_userinfotwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='求职者姓名')),
                ('iphone', models.CharField(max_length=11, verbose_name='求职者联系方式')),
                ('job', models.CharField(max_length=100, verbose_name='求职岗位')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '招聘信息',
                'verbose_name': '招聘信息',
            },
        ),
    ]
