# Generated by Django 2.0.9 on 2019-02-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0004_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfotwo',
            name='error',
            field=models.IntegerField(choices=[(0, '正确'), (1, '错误')], default=0, verbose_name='答题状态'),
        ),
    ]
